version: '3.8'

services:
  web:
    # Берем Dockerfile из каталога aitarget_test_task
    build: ./mylibrary
    expose:
      - 8000
    volumes:
      - static_volume:/app/static
    # Файл содержащий переменные для контейнера
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    # Образ и версия базы, которую мы будем использовать
    image: postgres:13.0-alpine
    # Внешний том(volume) и место где он будет подключен внутри контейнера
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/static
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  postgres_volume:
  static_volume: