FROM python:3.7-slim

RUN mkdir /app

COPY ./requirements.txt /app

RUN apt-get update && apt-get install -y netcat
RUN pip3 install -r /app/requirements.txt --no-cache-dir

COPY . /app

WORKDIR /app

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000" ]

ENTRYPOINT ["./entrypoint.dev.sh"]